<template>
  <div>
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/auto/auto1.jpg"
      src="~@/assets/img/auto/auto1.jpg"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/auto/auto2.jpg"
      src="~@/assets/img/auto/auto2.jpg"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/auto/auto3.jpg"
      src="~@/assets/img/auto/auto3.jpg"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/auto/auto4.jpg"
      src="~@/assets/img/auto/auto4.jpg"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/auto/auto5.jpg"
      src="~@/assets/img/auto/auto5.jpg"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/auto/auto6.jpg"
      src="~@/assets/img/auto/auto6.jpg"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/auto/auto7.jpg"
      src="~@/assets/img/auto/auto7.jpg"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/auto/auto8.jpg"
      src="~@/assets/img/auto/auto8.jpg"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/auto/auto9.jpg"
      src="~@/assets/img/auto/auto9.jpg"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/auto/auto10.jpg"
      src="~@/assets/img/auto/auto10.jpg"
    />
  </div>
</template>
