<template>
  <div>
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/pms/pms1.png"
      src="~@/assets/img/pms/pms1.png"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/pms/pms2.png"
      src="~@/assets/img/pms/pms2.png"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/pms/pms3.png"
      src="~@/assets/img/pms/pms3.png"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/pms/pms4.png"
      src="~@/assets/img/pms/pms4.png"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/pms/pms5.png"
      src="~@/assets/img/pms/pms5.png"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/pms/pms6.png"
      src="~@/assets/img/pms/pms6.png"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/pms/pms7.png"
      src="~@/assets/img/pms/pms7.png"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/pms/pms8.png"
      src="~@/assets/img/pms/pms8.png"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/pms/pms9.png"
      src="~@/assets/img/pms/pms9.png"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/pms/pms10.png"
      src="~@/assets/img/pms/pms10.png"
    />
    <v-img
      class="mb-5"
      lazy-src="~@/assets/img/pms/pms11.png"
      src="~@/assets/img/pms/pms11.png"
    />
  </div>
</template>
